### ISSUE TITLE
Traduzir o documento principal para o Ingles

### ISSUE THREAD

**Issue by gpupo** [gpupo-meta/dockerized-helloworld#1]
Traduzir README.md

**Comment by leochrisis** [comment]
Olá @gpupo 
Fiz a tradução solicitada nesta issue, vou abrir uma PR aqui. Espero ter ajudado.
Qualquer dúvida ou problema é só entrar em contato. :D

**Comment by gpupo** [comment]
Obrigado@leochrisis !
